os: unstable

environment:
  matrix:
    - nodejs_version: 8

cache:
  - "%LOCALAPPDATA%/Yarn"
  - node_modules -> package.json
  - app/node_modules -> app/package.json

matrix:
  fast_finish: true

build: off

version: '{build}'

shallow_clone: true

clone_depth: 1

install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - yarn --ignore-platform

test_script:
  - yarn package
  - yarn test-e2e
